# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r:
  matrix:
    - oldrel
    - release
    - devel
env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel