# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

os:
 - linux
 
r:
 - oldrel
 - release
 - devel

install:
  - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev

r_github_packages:
  - cran/rgl